### ISSUE TITLE
When routing from a `/skills/{skill_id}` page to `Team` the `team` path should not be added to the url

### ISSUE THREAD

**Issue by thebho** [maryvilledev/skilldirectoryui#79]
`http://ec2-54-147-37-162.compute-1.amazonaws.com:8000/skills/team`

**Comment by dane-johnson** [comment]
Did we not already fix this? I thought this was resolved by moving to absolute links.

**Comment by thebho** [comment]
It was still happening on Friday in the dev environment.
1. Select a skill
2. Select `Team` from the header
3. Refresh the page
